export const chadhawaTemples = [
  {
    id: "kaal-bhairav",
    name: "Kaal Bhairav Temple Puja",
    location: "Kaal Bhairav Temple, Varanasi",
    image: "/assets/img/Mandir-img/KaalBhairav .webp",
    link: "/chadhawaspageEng/kaalbhairavEng.html",
    devotees: "Sacred Puja",
    description: "Experience the divine energy of Lord Kaal Bhairav",
  },
  {
    id: "sankat-mochan",
    name: "Sankat Mochan Temple Puja",
    location: "Sankat Mochan Temple, Varanasi",
    image: "/assets/img/Mandir-img/SankatMochan.webp",
    link: "/chadhawaspageEng/SankatMochanMandirEnd.html",
    devotees: "Blessed Puja",
    description: "Seek blessings from Lord Hanuman for removing obstacles",
  },
  {
    id: "kashi-vishwanath",
    name: "Kashi Vishwanath Temple Puja",
    location: "Kashi Vishwanath Temple, Varanasi",
    image: "/assets/img/Mandir-img/KashiVishwanath.webp",
    link: "/chadhawaspageEng/Kashiwishwanath.html",
    devotees: "Divine Puja",
    description: "Worship Lord Shiva at the holiest temple in Varanasi",
  },
  {
    id: "mahalaxmi",
    name: "Mahalaxmi Temple Puja",
    location: "Mahalaxmi Temple, Varanasi",
    image: "/assets/img/Mandir-img/manglagori.webp",
    link: "/chadhawaspageEng/MahaLaxmimandir.html",
    devotees: "Prosperity Puja",
    description: "Goddess Mahalaxmi's blessings for wealth and prosperity",
  },
  {
    id: "chintamani",
    name: "Shree Chintamani Temple Puja",
    location: "Chintamani Temple, Varanasi",
    image: "/assets/img/Mandir-img/Chintamani.webp",
    link: "/chadhawaspageEng/ShriChintamani.html",
    devotees: "Wisdom Puja",
    description: "Seek wisdom and knowledge from Lord Ganesha",
  },
];
